- name: Get kubeadm join command from first k8s master
  shell: KUBECONFIG=/etc/kubernetes/admin.conf kubeadm token create --print-join-command
  register: kubeadm_join_command
  delegate_to: "{{ groups['k8s_masters'][0] }}"

- name: Run kubeadm join command on worker nodes
  shell: "{{ kubeadm_join_command.stdout }}"
