- name: needed packages for client machine
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - vim
    - wget

- name: Download cfssl_linux-amd6
  get_url:
    url: https://pkg.cfssl.org/R1.2/cfssl_linux-amd64
    dest: /usr/local/bin/cfssl
    mode: '0755'

- name: Download cfssljson_linux-amd64
  get_url:
    url: https://pkg.cfssl.org/R1.2/cfssljson_linux-amd64
    dest: /usr/local/bin/cfssljson
    mode: '0755'

# Installing kubectl
- name: Download cfssl_linux-amd6
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v{{ k8s_version }}/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
    mode: '0755'

# Certificates
- name: Copy ca-config.json
  copy:
    src: ca-config.json
    dest: ~/ca-config.json

- name: Copy ca-csr.json
  copy:
    src: ca-csr.json
    dest: ~/ca-csr.json

- name: Generate the certificate authority certificate and private key
  shell: cfssl gencert -initca ca-csr.json | cfssljson -bare ca

- name: Copy kubernetes-csr.json
  copy:
    src: kubernetes-csr.json
    dest: ~/kubernetes-csr.json

- name: Generate the certificate and private key.
  shell: cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -hostname=192.168.1.20,192.168.1.21,192.168.1.22,192.168.1.23,127.0.0.1,kubernetes.default -profile=kubernetes kubernetes-csr.json | cfssljson -bare kubernetes

- name: Copy certs to haproxy, master and etcd nodes
  shell: scp ca.pem kubernetes.pem kubernetes-key.pem "{{ item }}":~
  with_inventory_hostnames:
    - all

- name: copy id_rsa to master1
  shell: scp ~/.ssh/id_rsa root@"{{  groups['k8s_masters'][0] }}":~/.ssh/id_rsa
